### ISSUE TITLE
3D 物体目标生成

### ISSUE THREAD

**Issue by sditeng** [wuxiaolang/Cube_SLAM_wu#2]
您好，3D 物体目标生成的代码是那一块呢？

**Comment by wuxiaolang** [comment]
您好，主要在 `box_proposal_detail.cpp` 的 [detect_cuboid()](https://github.com/wuxiaolang/Cube_SLAM_wu/blob/master/detect_3d_cuboid/src/box_proposal_detail.cpp#L65) 函数中进行的。
